services:
  tfc-agent:
    image: hashicorp/tfc-agent:latest
#    container_name: tfc-agent
    platform: linux/arm64
    restart: unless-stopped
    env_file:
      - .env # Contains TFC_AGENT_TOKEN
    environment:
      TFC_AGENT_NAME: localhost-agent
      TFC_AGENT_SINGLE: true
      TFC_AGENT_LOG_LEVEL: info
      TFC_AGENT_AUTO_UPDATE: disabled
    deploy:
      replicas: 1
networks:
  default:
    name: docker-vault-stack
    external: true